INSERT INTO "tblOccupation" VALUES(1,'Farmer/Cultivator','K…lK ');
INSERT INTO "tblOccupation" VALUES(2,'Homemaker','N‡i KvR K‡i ');
INSERT INTO "tblOccupation" VALUES(3,'Agri-labor','K…wl kªwgK ');
INSERT INTO "tblOccupation" VALUES(4,'Non-agri labor','kªwgK (K…wl kªwgK Qvov)  ');
INSERT INTO "tblOccupation" VALUES(5,'Salaried job (vt./Private/N)','‡eZbfy³ Kg©KZv©/Kg©Pvix (miKvix/cÖvB‡fU/Gb.wR.I.)');
INSERT INTO "tblOccupation" VALUES(6,'Mason (Rajmistri)',' ivRwg¯¿x ');
INSERT INTO "tblOccupation" VALUES(7,'Carpenter','KvV wg¯¿x ');
INSERT INTO "tblOccupation" VALUES(8,'Van/Rickshaw puller','f¨vb/wiKkv PvjK ');
INSERT INTO "tblOccupation" VALUES(9,'Fisherma','‡R‡j ');
INSERT INTO "tblOccupation" VALUES(10,'Boatma','‡bŠKv PvjK/gvwS ');
INSERT INTO "tblOccupation" VALUES(11,'Blacksmith ','Kg©Kvi ');
INSERT INTO "tblOccupation" VALUES(12,'ldsmith','¯^Y©Kvi ');
INSERT INTO "tblOccupation" VALUES(13,'Potter (soil smith)','Kzgvi/Kz¤¢Kvi ');
INSERT INTO "tblOccupation" VALUES(14,'Shoe polish /maker','gywP');
INSERT INTO "tblOccupation" VALUES(15,'Shopkeeper','‡`vKvb`vi ');
INSERT INTO "tblOccupation" VALUES(16,'Vendor (Feriwala/howker)',' ‡dwiIqvjv ');
INSERT INTO "tblOccupation" VALUES(17,'Petty trader (capital <=10,000 Tk)','¶y`ª e¨emvqx (g~jab <=10000)  ');
INSERT INTO "tblOccupation" VALUES(18,'Business(capital >10,000 Tk)','e¨emvqx (g~jab >10000)  ');
INSERT INTO "tblOccupation" VALUES(19,'Tailor','`wR© ');
INSERT INTO "tblOccupation" VALUES(20,'Driver','WªvBfvi');
INSERT INTO "tblOccupation" VALUES(21,'Cottage industry',' KzUxi wkí  ');
INSERT INTO "tblOccupation" VALUES(22,'Poultry /livestock rearer','‡cvjwUª/ e¨emvi Rb¨ cï jvjb-cvjbKvix ');
INSERT INTO "tblOccupation" VALUES(23,'Electricia','‰e`y¨wZK wg¯¿x  ');
INSERT INTO "tblOccupation" VALUES(24,'Homeopath','‡nvwgIc¨vw_ Wv³vi  ');
INSERT INTO "tblOccupation" VALUES(25,'Spiritual healer/kabiraj/ Ojha','Ava¨vwZK wPwKrmK/ KweivR/ ISuv ');
INSERT INTO "tblOccupation" VALUES(26,'Professional practitioner (Doctor/lawyer)','‡ckv`vi Wv³vi/DwKj ');
INSERT INTO "tblOccupation" VALUES(27,'Imam/priest',' Bgvg/ ag©hvRK ');
INSERT INTO "tblOccupation" VALUES(28,'Retired service holder','AemicÖvß PvKzixRxex ');
INSERT INTO "tblOccupation" VALUES(29,'Student','QvÎ');
INSERT INTO "tblOccupation" VALUES(30,'Unemployed','‡eKvi ');
INSERT INTO "tblOccupation" VALUES(31,'Differently able','wfbè avivq m¶g');
INSERT INTO "tblOccupation" VALUES(32,'Domestic maid / servant','Kv‡Ri †jvK ');
INSERT INTO "tblOccupation" VALUES(33,'Landlord (Provide land for farmers for sharecropping or others)','Rwg`vi (km¨ Drcv`b A_ev Ab¨ †Kvb Kv‡R K…lK‡`i Rwg eM©v †`q) ');
INSERT INTO "tblOccupation" VALUES(34,'Staying abroad','we‡`‡k _v‡K ');
INSERT INTO "tblOccupation" VALUES(35,'Died/untraced','g„Z/wb‡LuvR  ');
INSERT INTO "tblOccupation" VALUES(36,'Begger','wf¶zK');
INSERT INTO "tblOccupation" VALUES(37,'Teacher','wk¶K');
INSERT INTO "tblOccupation" VALUES(77,'Others (specify)','Ab¨vb¨(wbw`©ó K‡i wjLyb)');
INSERT INTO "tblOccupation" VALUES(99,'Don’t know','Rvwbbv');
