INSERT INTO "tblUnion" VALUES('1','1','1','1.  Rangpur');
INSERT INTO "tblUnion" VALUES('1','1','2','2.  Khornia');
INSERT INTO "tblUnion" VALUES('1','1','3','3.  Dumuria');
INSERT INTO "tblUnion" VALUES('1','1','4','4.  Dhamalia');
INSERT INTO "tblUnion" VALUES('1','1','5','5.  Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('1','2','6','1. Deluty');
INSERT INTO "tblUnion" VALUES('1','2','7','2.  Sholadana');
INSERT INTO "tblUnion" VALUES('1','2','8','3.  Lata');
INSERT INTO "tblUnion" VALUES('1','2','9','4.  Kopilmuni');
INSERT INTO "tblUnion" VALUES('1','2','10','5.  Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('2','3','11','1.  Payra');
INSERT INTO "tblUnion" VALUES('2','3','12','2.  Sundoli');
INSERT INTO "tblUnion" VALUES('2','3','13','3.  Chalisia');
INSERT INTO "tblUnion" VALUES('2','3','14','4.  Baghutia');
INSERT INTO "tblUnion" VALUES('2','3','15','5. Shovapara');
INSERT INTO "tblUnion" VALUES('2','3','16','6. Shreedharpur');
INSERT INTO "tblUnion" VALUES('2','3','17','7. Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('2','4','18','1. Khanpur');
INSERT INTO "tblUnion" VALUES('2','4','19','2. Durbadanga');
INSERT INTO "tblUnion" VALUES('2','4','20','3.  Kultia');
INSERT INTO "tblUnion" VALUES('2','4','21','4.  Bhojgati');
INSERT INTO "tblUnion" VALUES('2','4','22','5.  Khedapara');
INSERT INTO "tblUnion" VALUES('2','4','23','6.  Kashimnagar');
INSERT INTO "tblUnion" VALUES('2','4','24','7. Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('3','1','25','1. Batiaghata');
INSERT INTO "tblUnion" VALUES('3','1','26','2. Gangarampur');
INSERT INTO "tblUnion" VALUES('3','1','27','3.  Surkhali');
INSERT INTO "tblUnion" VALUES('3','2','28','1. Dumuria sadar');
INSERT INTO "tblUnion" VALUES('3','2','29','2.  Gutudia');
INSERT INTO "tblUnion" VALUES('3','2','30','3. Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('3','3','31','1.  Jalma');
INSERT INTO "tblUnion" VALUES('3','3','32','2. Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('4','4','33','1. Morichbunia');
INSERT INTO "tblUnion" VALUES('4','4','34','2.  Madarbunia');
INSERT INTO "tblUnion" VALUES('4','4','35','3.  Auliapur');
INSERT INTO "tblUnion" VALUES('4','4','36','4. Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('4','5','37','1. Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('4','6','38','1. Others Union (Specify)');
INSERT INTO "tblUnion" VALUES('4','7','39','1. Others Union (Specify)');
